n=input('Digite algo: ')
print('Qual o tipo?')
print(type(n))
print('É um número?')
print(n.isnumeric())
print('É um letra?')
print(n.isalpha())
print('Está somente com letras maicusculas?')
print(n.isupper())